name: Deploy Azure Function

on:
  push:
    branches:
      - main
    paths:
      - 'handlenett-backend/serverless/CosmosDBChangeFeed/**'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Azure Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.AZURE_ACR_REGISTRY_URL }}
          username: ${{ secrets.AZURE_ACR_USERNAME }}
          password: ${{ secrets.AZURE_ACR_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: handlenett-backend/functions/YourFunctionProjectPath  # Update to the path of your function project
          push: true
          tags: |
            ${{ secrets.AZURE_ACR_REGISTRY_URL }}/handlenett-function-cosmosdb-changefeed:latest
            ${{ secrets.AZURE_ACR_REGISTRY_URL }}/handlenett-function-cosmosdb-changefeed:${{ github.sha }}

      - name: Log in to Azure - App Registration Credentials
        uses: azure/login@v1
        with:
          creds: |
            {
              "clientId": "${{ secrets.AZURE_CLIENT_ID_BACKEND_WEB_API }}",
              "clientSecret": "${{ secrets.AZURE_SECRET_ID_BACKEND_WEB_API }}",
              "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
              "tenantId": "${{ secrets.AZURE_TENANT_ID }}"
            }

      - name: Update Azure Function App with new image
        run: |
          az functionapp config container set --name handlenett-notifications-fa --resource-group handlenett-rg \
            --docker-custom-image-name ${{ secrets.AZURE_ACR_REGISTRY_URL }}/handlenett-function:${{ github.sha }}
