name: Deploy Azure Function

on:
  push:
    paths:
      - 'handlenett-backend/serverless/HandlenettNotifications/**'
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Log in to Azure - App Registration Credentials
        uses: azure/login@v1
        with:
          creds: |
            {
              "clientId": "${{ secrets.AZURE_CLIENT_ID_PUBLISH_AND_DEPLOY_AR }}",
              "clientSecret": "${{ secrets.AZURE_SECRET_ID_PUBLISH_AND_DEPLOY_AR }}",
              "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
              "tenantId": "${{ secrets.AZURE_TENANT_ID }}"
            }
      
      - name: Build the function app
        run: dotnet publish handlenett-backend/serverless/HandlenettNotifications -c Release -o ./publish

      - name: List published files
        run: dir ./publish

      - name: Deploy to Azure Function App using GitHub Action
        uses: Azure/functions-action@v1
        with:
          app-name: 'handlenett-notifications-fa'
          package: './publish'
