name: Build and Deploy to Azure Web App

on:
  push:
    branches:
      - main
    paths:
      - 'handlenett-backend/web-api/HandlenettAPI/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Azure Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.AZURE_ACR_REGISTRY_URL }}
          username: ${{ secrets.AZURE_ACR_USERNAME }} 
          password: ${{ secrets.AZURE_ACR_PASSWORD }} 

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: handlenett-backend/web-api/HandlenettAPI
          push: true
          tags: ${{ secrets.AZURE_ACR_REGISTRY_URL  }}/handlenett-api:latest

      # - name: Deploy to Azure Web App
      #   uses: azure/webapps-deploy@v2
      #   with:
      #     app-name: handlenett-api
      #     slot-name: production
      #     publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
      #     images: ${{ secrets.AZURE_CR_NAME_BACKEND_WEB_API }}.azurecr.io/handlenett-api:latest
